export const CHARACTERS_GET = 'CHARACTERS_GET'
export const CHARACTERS_SET = 'CHARACTERS_SET'
export const CHARACTERS_LOADING = 'CHARACTERS_LOADING'
export const CHARACTERS_ERROR = 'CHARACTERS_ERROR'

export const CHARACTERS_SELECTED = 'CHARACTERS_SELECTED'
export const CHARACTERS_SELECTED_CHANGE = 'CHARACTERS_SELECTED_CHANGE'

export const SEARCH_ERROR = 'SEARCH_ERROR'
export const SET_SEARCH_ERROR = 'SET_SEARCH_ERROR'
