import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Chiva's Bar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          <h2>dia</h2>
          <p>Lunes</p>
        </div>
        <div>
          <h2>Horario</h2>
          <p>05:00 pm a 11:00 pm</p>
        </div>
      </main>      

    </>
  )
}
