import Head from 'next/head'
import productsBeers from "../data/productsBeers.json"
import productsLiqueurs from "../data/productsLiqueurs.json"
import productsDrinks from "../data/productsDrinks.json"
import { useEffect, useState } from 'react'

export default function Home() {

  const [products, setProducts] = useState({
    Beers: [],
    Liqueurs: [],
    Drinks: []
  })

  const handleSort = (list) => {

    list.sort(function(a, b) {
        return (a.order - b.order);
    }).sort(function(a, b) {
        return (a.name - b.name);
    });

    return list
  }

  useEffect(() => {
    setProducts({
      Beers: handleSort(productsBeers.filter((item) => !item.hide )),
      Liqueurs: handleSort(productsLiqueurs.filter((item) => !item.hide )),
      Drinks: handleSort(productsDrinks.filter((item) => !item.hide ))
    })
  }, [])

  return (
    <>
      <Head>
        <title>{`Chiva's Bar`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='products_container'>
        <div>
          <h2 className='products_container--header'>Cervezas</h2>
          {
            products.Beers.map( product => (
              <div key={product.id}>
                <div className='products_container--body'>
                  <p className='product--item product--item-name'>{product.productName}</p>
                  <p className='product--item product--item-price'>{`$ ${product.price.toLocaleString()}`}</p>        
                </div>
                <div className='product--divider'></div>
              </div>
            ))
          }
        </div>
        <div>
          <h2 className='products_container--header'>Licores</h2>
          {
            products.Liqueurs.map( product => (
              <div key={product.id}>
                <div className='products_container--body'>
                  <p className='product--item product--item-name'>{product.productName}</p>
                  <p className='product--item product--item-price'>{`$ ${product.price.toLocaleString()}`}</p>        
                </div>
               <div className='product--divider'></div>
              </div>
            ))
          }
        </div>
        <div>
          <h2 className='products_container--header'>Bebidas</h2>
          {
            products.Drinks.map( product => (
              <div key={product.id}>
                <div className='products_container--body'>
                  <p className='product--item product--item-name'>{product.productName}</p>
                  <p className='product--item product--item-price'>{`$ ${product.price.toLocaleString()}`}</p>        
                </div>
               <div className='product--divider'></div>
              </div>
            ))
          }
        </div>
      
      </div>
    </>
  )
}
