import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Chiva's Bar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        Productos
      </main>      

    </>
  )
}
